import type { ServicePriceType } from '@/types'

export type ServiceCatalogCategoryKey =
  | 'primary-preventive'
  | 'urgent-emergency'
  | 'telehealth-virtual'
  | 'diagnostics-lab'
  | 'mental-health'
  | 'womens-health'
  | 'pediatrics'
  | 'dental'
  | 'dermatology'
  | 'orthopedics-pt'
  | 'nutrition-wellness'
  | 'eye-care'
  | 'cardiology'

export type ServiceCatalogTemplate = {
  key: string
  category: ServiceCatalogCategoryKey
  name: string
  description: string
  durationMinutes: number
  priceType: ServicePriceType
  price?: number | null
  priceMin?: number | null
  priceMax?: number | null
}

export const SERVICE_CATALOG_CATEGORIES: Array<{ key: 'all' | ServiceCatalogCategoryKey; label: string }> = [
  { key: 'all', label: 'All Specialties' },
  { key: 'primary-preventive', label: 'Primary & Preventive Care' },
  { key: 'urgent-emergency', label: 'Urgent & Emergency Care' },
  { key: 'telehealth-virtual', label: 'Telehealth & Virtual Care' },
  { key: 'diagnostics-lab', label: 'Diagnostics & Lab' },
  { key: 'mental-health', label: 'Mental Health' },
  { key: 'womens-health', label: "Women's Health" },
  { key: 'pediatrics', label: 'Pediatrics' },
  { key: 'dental', label: 'Dental' },
  { key: 'dermatology', label: 'Dermatology' },
  { key: 'orthopedics-pt', label: 'Orthopedics & PT' },
  { key: 'nutrition-wellness', label: 'Nutrition & Wellness' },
  { key: 'eye-care', label: 'Eye Care' },
  { key: 'cardiology', label: 'Cardiology' },
]

const PRIMARY_PREVENTIVE: ServiceCatalogTemplate[] = [
  {
    key: 'general-consultation',
    category: 'primary-preventive',
    name: 'General Consultation',
    description: 'Comprehensive consultation with a general practitioner for diagnosis, treatment planning, and referrals.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 120,
  },
  {
    key: 'annual-physical-exam',
    category: 'primary-preventive',
    name: 'Annual Physical Exam',
    description: 'Full-body preventive health check with vitals, bloodwork review, and wellness assessment.',
    durationMinutes: 60,
    priceType: 'fixed',
    price: 200,
  },
  {
    key: 'follow-up-visit',
    category: 'primary-preventive',
    name: 'Follow-Up Visit',
    description: 'Short revisit to review test results, adjust treatments, or check on a previously evaluated condition.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 80,
  },
  {
    key: 'chronic-disease-management',
    category: 'primary-preventive',
    name: 'Chronic Disease Management',
    description: 'Ongoing follow-up for diabetes, hypertension, asthma, COPD, and similar long-term conditions.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 130,
  },
  {
    key: 'preventive-wellness-screening',
    category: 'primary-preventive',
    name: 'Preventive Wellness Screening',
    description: 'Risk assessment and screening for cardiovascular disease, cancer markers, and metabolic disorders.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'sick-visit-acute-care',
    category: 'primary-preventive',
    name: 'Sick Visit / Acute Care',
    description: 'Same-day evaluation for fever, cold, flu, infections, rashes, minor injuries, and acute illnesses.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 100,
  },
  {
    key: 'medication-management',
    category: 'primary-preventive',
    name: 'Medication Management',
    description: 'Review and adjustment of prescriptions, dosage changes, and potential drug interactions.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 90,
  },
  {
    key: 'vaccination-immunization',
    category: 'primary-preventive',
    name: 'Vaccination / Immunization',
    description: 'Flu shots, COVID boosters, hepatitis, travel vaccines, shingles, pneumonia, and routine immunizations.',
    durationMinutes: 15,
    priceType: 'starting_at',
    priceMin: 30,
    priceMax: 120,
  },
]

const URGENT_EMERGENCY: ServiceCatalogTemplate[] = [
  {
    key: 'urgent-care-visit',
    category: 'urgent-emergency',
    name: 'Urgent Care Visit',
    description: 'Walk-in or same-day care for non-life-threatening injuries and acute illnesses requiring prompt attention.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'wound-care-laceration-repair',
    category: 'urgent-emergency',
    name: 'Wound Care & Laceration Repair',
    description: 'Cleaning, suturing, stapling, and dressing of cuts, lacerations, and abrasions.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 200,
  },
  {
    key: 'fracture-sprain-assessment',
    category: 'urgent-emergency',
    name: 'Fracture & Sprain Assessment',
    description: 'X-ray evaluation, splinting, and casting for suspected fractures and sprains.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 250,
  },
  {
    key: 'iv-fluids-infusion-therapy',
    category: 'urgent-emergency',
    name: 'IV Fluids & Infusion Therapy',
    description: 'Intravenous fluid hydration, electrolyte replacement, and outpatient infusion services.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 300,
  },
  {
    key: 'rapid-diagnostic-testing',
    category: 'urgent-emergency',
    name: 'Rapid Diagnostic Testing',
    description: 'On-site rapid strep, flu, COVID, mono, and urinalysis tests with immediate results.',
    durationMinutes: 20,
    priceType: 'starting_at',
    priceMin: 40,
    priceMax: 120,
  },
]

const TELEHEALTH_VIRTUAL: ServiceCatalogTemplate[] = [
  {
    key: 'telehealth-consultation',
    category: 'telehealth-virtual',
    name: 'Telehealth Consultation',
    description: 'Secure video or phone appointment with a licensed provider from anywhere - no travel needed.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 75,
  },
  {
    key: 'virtual-follow-up',
    category: 'telehealth-virtual',
    name: 'Virtual Follow-Up',
    description: 'Video follow-up to review labs, imaging results, or ongoing treatment plans remotely.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 55,
  },
  {
    key: 'prescription-refill-request',
    category: 'telehealth-virtual',
    name: 'Prescription Refill Request',
    description: 'Remote review and renewal of maintenance medications without an in-office visit.',
    durationMinutes: 10,
    priceType: 'fixed',
    price: 40,
  },
  {
    key: 'online-mental-health-session',
    category: 'telehealth-virtual',
    name: 'Online Mental Health Session',
    description: 'Video therapy or psychiatric consultation from the comfort and privacy of home.',
    durationMinutes: 50,
    priceType: 'starting_at',
    price: 120,
  },
  {
    key: 'chronic-condition-check-in',
    category: 'telehealth-virtual',
    name: 'Chronic Condition Check-In',
    description: 'Virtual monitoring visit for patients managing long-term conditions like diabetes or hypertension.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 65,
  },
]

const DIAGNOSTICS_LAB: ServiceCatalogTemplate[] = [
  {
    key: 'comprehensive-blood-panel',
    category: 'diagnostics-lab',
    name: 'Comprehensive Blood Panel',
    description: 'Full CBC, metabolic panel, lipid profile, thyroid, HbA1c, and other blood tests with provider review.',
    durationMinutes: 20,
    priceType: 'starting_at',
    price: 80,
  },
  {
    key: 'urinalysis',
    category: 'diagnostics-lab',
    name: 'Urinalysis',
    description: 'Complete urine analysis to detect infections, kidney issues, diabetes markers, and other conditions.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 45,
  },
  {
    key: 'sti-std-panel',
    category: 'diagnostics-lab',
    name: 'STI / STD Panel',
    description: 'Confidential testing for HIV, chlamydia, gonorrhea, syphilis, herpes, and hepatitis.',
    durationMinutes: 20,
    priceType: 'starting_at',
    price: 95,
  },
  {
    key: 'x-ray-imaging',
    category: 'diagnostics-lab',
    name: 'X-Ray Imaging',
    description: 'Digital X-ray for chest, extremities, spine, and other areas with same-day results.',
    durationMinutes: 20,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'ultrasound',
    category: 'diagnostics-lab',
    name: 'Ultrasound',
    description: 'Diagnostic ultrasound imaging for abdomen, pelvis, thyroid, vascular, and musculoskeletal conditions.',
    durationMinutes: 30,
    priceType: 'starting_at',
    priceMin: 200,
    priceMax: 500,
  },
  {
    key: 'ecg-ekg',
    category: 'diagnostics-lab',
    name: 'ECG / EKG',
    description: 'Electrocardiogram to evaluate heart rhythm, detect arrhythmias, and assess cardiac health.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 120,
  },
]

const MENTAL_HEALTH: ServiceCatalogTemplate[] = [
  {
    key: 'psychiatric-evaluation',
    category: 'mental-health',
    name: 'Psychiatric Evaluation',
    description: 'Comprehensive mental health assessment for diagnosis and treatment planning by a psychiatrist.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 250,
  },
  {
    key: 'individual-therapy-session',
    category: 'mental-health',
    name: 'Individual Therapy Session',
    description: 'One-on-one psychotherapy session with a licensed therapist for CBT, DBT, or other modalities.',
    durationMinutes: 50,
    priceType: 'starting_at',
    priceMin: 120,
    priceMax: 200,
  },
  {
    key: 'couples-therapy',
    category: 'mental-health',
    name: 'Couples Therapy',
    description: 'Joint therapy sessions to improve communication, resolve conflicts, and strengthen relationships.',
    durationMinutes: 60,
    priceType: 'starting_at',
    priceMin: 150,
    priceMax: 250,
  },
  {
    key: 'group-therapy-session',
    category: 'mental-health',
    name: 'Group Therapy Session',
    description: 'Facilitated group support for anxiety, depression, grief, addiction recovery, and more.',
    durationMinutes: 90,
    priceType: 'starting_at',
    priceMin: 40,
    priceMax: 80,
  },
  {
    key: 'medication-assisted-therapy',
    category: 'mental-health',
    name: 'Medication-Assisted Therapy',
    description: 'Psychiatric medication management combined with ongoing therapeutic support and monitoring.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'psychological-assessment',
    category: 'mental-health',
    name: 'Psychological Assessment',
    description: 'Comprehensive psychometric testing for ADHD, learning disabilities, autism, and cognitive function.',
    durationMinutes: 120,
    priceType: 'starting_at',
    price: 400,
  },
]

const WOMENS_HEALTH: ServiceCatalogTemplate[] = [
  {
    key: 'well-woman-exam',
    category: 'womens-health',
    name: 'Well-Woman Exam',
    description: 'Routine preventive visit covering reproductive health, screenings, and counseling.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 135,
  },
  {
    key: 'birth-control-consultation',
    category: 'womens-health',
    name: 'Birth Control Consultation',
    description: 'Discussion of contraception options, side effects, and personalized family planning.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 90,
  },
  {
    key: 'prenatal-intake',
    category: 'womens-health',
    name: 'Prenatal Intake',
    description: 'Initial pregnancy visit covering history, labs, expected timeline, and care planning.',
    durationMinutes: 40,
    priceType: 'fixed',
    price: 150,
  },
  {
    key: 'menopause-management',
    category: 'womens-health',
    name: 'Menopause Management',
    description: 'Assessment and treatment of menopause symptoms, hormone concerns, and wellness goals.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 175,
  },
  {
    key: 'pap-smear-cervical-screening',
    category: 'womens-health',
    name: 'Pap Smear / Cervical Screening',
    description: 'Cervical cancer screening and preventive gynecologic exam.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 120,
  },
]

const PEDIATRICS: ServiceCatalogTemplate[] = [
  {
    key: 'well-child-visit',
    category: 'pediatrics',
    name: 'Well-Child Visit',
    description: 'Developmental milestone assessment, growth monitoring, vaccinations, and parent guidance by age.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 160,
  },
  {
    key: 'sick-child-visit',
    category: 'pediatrics',
    name: 'Sick Child Visit',
    description: 'Same-day evaluation for fever, ear infections, coughs, rashes, and acute childhood illnesses.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 110,
  },
  {
    key: 'school-sports-physical',
    category: 'pediatrics',
    name: 'School / Sports Physical',
    description: 'Annual clearance physical for school enrollment, sports participation, and camp requirements.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 90,
  },
  {
    key: 'newborn-exam',
    category: 'pediatrics',
    name: 'Newborn Exam',
    description: 'Comprehensive newborn assessment for weight, reflexes, feeding, jaundice, and overall health.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 150,
  },
  {
    key: 'childhood-vaccine-package',
    category: 'pediatrics',
    name: 'Childhood Vaccine Package',
    description: 'DTaP, MMR, varicella, polio, hepatitis, and HPV vaccinations per CDC immunization schedule.',
    durationMinutes: 20,
    priceType: 'starting_at',
    priceMin: 30,
    priceMax: 100,
  },
  {
    key: 'adhd-evaluation-management',
    category: 'pediatrics',
    name: 'ADHD Evaluation & Management',
    description: 'Behavioral assessment, parent/teacher input forms, and medication management for ADHD.',
    durationMinutes: 60,
    priceType: 'starting_at',
    price: 200,
  },
  {
    key: 'developmental-screening',
    category: 'pediatrics',
    name: 'Developmental Screening',
    description: 'Age-appropriate screening for speech, motor, social, and learning development.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 130,
  },
]

const DENTAL: ServiceCatalogTemplate[] = [
  {
    key: 'dental-consultation',
    category: 'dental',
    name: 'Dental Consultation',
    description: 'Initial dental evaluation, treatment planning, and discussion of oral health concerns.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 95,
  },
  {
    key: 'cleaning-checkup',
    category: 'dental',
    name: 'Cleaning & Checkup',
    description: 'Routine cleaning, oral exam, and preventive dental maintenance.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 120,
  },
  {
    key: 'root-canal-treatment',
    category: 'dental',
    name: 'Root Canal Treatment',
    description: 'Endodontic treatment to remove infected pulp, relieve pain, and save the natural tooth.',
    durationMinutes: 90,
    priceType: 'starting_at',
    priceMin: 700,
    priceMax: 1500,
  },
  {
    key: 'tooth-extraction',
    category: 'dental',
    name: 'Tooth Extraction',
    description: 'Simple or surgical removal of a damaged or impacted tooth.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 180,
  },
  {
    key: 'cosmetic-whitening',
    category: 'dental',
    name: 'Cosmetic Whitening',
    description: 'In-office whitening treatment for a brighter smile.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 250,
  },
  {
    key: 'emergency-dental-visit',
    category: 'dental',
    name: 'Emergency Dental Visit',
    description: 'Urgent treatment for tooth pain, swelling, broken restorations, or dental trauma.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'bite-alignment-assessment',
    category: 'dental',
    name: 'Bite / Alignment Assessment',
    description: 'Assessment of jaw alignment, bite issues, and orthodontic referral needs.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 140,
  },
]

const DERMATOLOGY: ServiceCatalogTemplate[] = [
  {
    key: 'skin-check-mole-exam',
    category: 'dermatology',
    name: 'Skin Check / Mole Exam',
    description: 'Full or targeted skin exam to evaluate moles, lesions, and suspicious skin changes.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 110,
  },
  {
    key: 'acne-consultation',
    category: 'dermatology',
    name: 'Acne Consultation',
    description: 'Evaluation of acne severity with tailored treatment and skincare recommendations.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 95,
  },
  {
    key: 'rashes-eczema-visit',
    category: 'dermatology',
    name: 'Rashes / Eczema Visit',
    description: 'Evaluation of skin rashes, dermatitis, eczema, and inflammatory skin conditions.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 100,
  },
  {
    key: 'mole-removal-consultation',
    category: 'dermatology',
    name: 'Mole Removal Consultation',
    description: 'Discussion of removal options for benign or suspicious moles and lesions.',
    durationMinutes: 20,
    priceType: 'starting_at',
    price: 250,
  },
  {
    key: 'cosmetic-botox-injectables',
    category: 'dermatology',
    name: 'Cosmetic Botox / Injectables',
    description: 'Aesthetic treatment consultation for wrinkle reduction and facial balance.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 300,
  },
]

const ORTHOPEDICS_PT: ServiceCatalogTemplate[] = [
  {
    key: 'orthopedic-consultation',
    category: 'orthopedics-pt',
    name: 'Orthopedic Consultation',
    description: 'Assessment of joint, bone, and musculoskeletal pain with imaging and treatment planning.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 150,
  },
  {
    key: 'physical-therapy-evaluation',
    category: 'orthopedics-pt',
    name: 'Physical Therapy Evaluation',
    description: 'Initial rehabilitation assessment focused on movement, strength, and recovery goals.',
    durationMinutes: 45,
    priceType: 'fixed',
    price: 130,
  },
  {
    key: 'sports-injury-assessment',
    category: 'orthopedics-pt',
    name: 'Sports Injury Assessment',
    description: 'Evaluation of sprains, strains, overuse injuries, and athletic recovery needs.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 200,
  },
  {
    key: 'back-neck-pain-visit',
    category: 'orthopedics-pt',
    name: 'Back & Neck Pain Visit',
    description: 'Focused exam for chronic or acute spine-related pain and mobility issues.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 140,
  },
  {
    key: 'post-op-rehab-follow-up',
    category: 'orthopedics-pt',
    name: 'Post-Op Rehab Follow-Up',
    description: 'Post-surgical recovery check-in to track mobility, pain, and therapy progression.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 110,
  },
]

const NUTRITION_WELLNESS: ServiceCatalogTemplate[] = [
  {
    key: 'nutritional-consultation',
    category: 'nutrition-wellness',
    name: 'Nutritional Consultation',
    description: 'Personalized dietary assessment and meal planning with a registered dietitian.',
    durationMinutes: 60,
    priceType: 'fixed',
    price: 120,
  },
  {
    key: 'weight-management-program',
    category: 'nutrition-wellness',
    name: 'Weight Management Program',
    description: 'Structured weight loss or gain program with medical oversight, labs, and dietitian coaching.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 150,
  },
  {
    key: 'iv-vitamin-therapy',
    category: 'nutrition-wellness',
    name: 'IV Vitamin Therapy',
    description: 'Custom intravenous infusion of vitamins, minerals, and antioxidants for energy and wellness.',
    durationMinutes: 45,
    priceType: 'starting_at',
    priceMin: 100,
    priceMax: 300,
  },
  {
    key: 'hormone-replacement-therapy',
    category: 'nutrition-wellness',
    name: 'Hormone Replacement Therapy',
    description: 'Evaluation and management of hormone deficiencies with bioidentical or synthetic hormone therapy.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 200,
  },
  {
    key: 'smoking-cessation-program',
    category: 'nutrition-wellness',
    name: 'Smoking Cessation Program',
    description: 'Medical and behavioral support including nicotine replacement therapy and counseling.',
    durationMinutes: 30,
    priceType: 'starting_at',
    price: 80,
  },
]

const EYE_CARE: ServiceCatalogTemplate[] = [
  {
    key: 'routine-eye-exam',
    category: 'eye-care',
    name: 'Routine Eye Exam',
    description: 'Comprehensive vision exam and preventive eye health screening.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 95,
  },
  {
    key: 'contact-lens-fitting',
    category: 'eye-care',
    name: 'Contact Lens Fitting',
    description: 'Assessment and fitting for standard or specialty contact lenses.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 125,
  },
  {
    key: 'vision-screening',
    category: 'eye-care',
    name: 'Vision Screening',
    description: 'Quick screening for acuity, refraction issues, and referral needs.',
    durationMinutes: 15,
    priceType: 'fixed',
    price: 60,
  },
  {
    key: 'dry-eye-follow-up',
    category: 'eye-care',
    name: 'Dry Eye Follow-Up',
    description: 'Follow-up evaluation for dry eye symptoms, treatment response, and care adjustments.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 80,
  },
]

const CARDIOLOGY: ServiceCatalogTemplate[] = [
  {
    key: 'cardiology-consultation',
    category: 'cardiology',
    name: 'Cardiology Consultation',
    description: 'Cardiac evaluation for chest pain, palpitations, blood pressure concerns, and heart risk review.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 180,
  },
  {
    key: 'hypertension-follow-up',
    category: 'cardiology',
    name: 'Hypertension Follow-Up',
    description: 'Blood pressure review, medication adjustment, and cardiovascular risk counseling.',
    durationMinutes: 20,
    priceType: 'fixed',
    price: 120,
  },
  {
    key: 'heart-rhythm-assessment',
    category: 'cardiology',
    name: 'Heart Rhythm Assessment',
    description: 'Evaluation of arrhythmia symptoms, ECG review, and next-step planning.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 220,
  },
  {
    key: 'echocardiogram-review',
    category: 'cardiology',
    name: 'Echocardiogram Review',
    description: 'Review of cardiac imaging results and treatment recommendations.',
    durationMinutes: 30,
    priceType: 'fixed',
    price: 260,
  },
  {
    key: 'preventive-heart-screening',
    category: 'cardiology',
    name: 'Preventive Heart Screening',
    description: 'Cardiovascular risk screening for cholesterol, blood pressure, and family history concerns.',
    durationMinutes: 45,
    priceType: 'starting_at',
    price: 150,
  },
]

export const SERVICE_CATALOG_TEMPLATES: ServiceCatalogTemplate[] = [
  ...PRIMARY_PREVENTIVE,
  ...URGENT_EMERGENCY,
  ...TELEHEALTH_VIRTUAL,
  ...DIAGNOSTICS_LAB,
  ...MENTAL_HEALTH,
  ...WOMENS_HEALTH,
  ...PEDIATRICS,
  ...DENTAL,
  ...DERMATOLOGY,
  ...ORTHOPEDICS_PT,
  ...NUTRITION_WELLNESS,
  ...EYE_CARE,
  ...CARDIOLOGY,
]
